---
# Sample Authelia configuration (v4.38+) to try out the GUI.
theme: light
server:
  address: 'tcp://:9091'
log:
  level: info
authentication_backend:
  file:
    path: /config/users_database.yml
access_control:
  default_policy: deny
  rules:
    - domain: 'public.example.com'
      policy: bypass
    - domain: 'secure.example.com'
      policy: two_factor
      subject:
        - 'group:admins'
session:
  name: authelia_session
  expiration: '1h'
  inactivity: '5m'
  remember_me: '1M'
  cookies:
    - domain: 'example.com'
      authelia_url: 'https://auth.example.com'
identity_providers:
  oidc:
    hmac_secret: 'insecure_secret_change_me'
    jwks:
      - key_id: default
        algorithm: RS256
        use: sig
        key: |
          -----BEGIN PRIVATE KEY-----
          REPLACE_WITH_YOUR_PRIVATE_KEY
          -----END PRIVATE KEY-----
    clients:
      - client_id: 'grafana'
        client_name: 'Grafana'
        client_secret: '$pbkdf2-sha512$310000$saltsaltsaltsalt$hashhashhash'
        public: false
        authorization_policy: two_factor
        consent_mode: explicit
        redirect_uris:
          - 'https://grafana.example.com/login/generic_oauth'
        scopes:
          - openid
          - profile
          - email
          - groups
storage:
  local:
    path: /config/db.sqlite3
notifier:
  filesystem:
    filename: /config/notification.txt
